export const AUTH_USER = 'auth_user',
  UNAUTH_USER = 'unauth_user',
  USER_EXIST = 'user_exist',
  SET_CURRENT_USER = 'set_current_user',
  EMAIL_EXIST = 'email_exist',
  ADD_RECIPE = 'add_recipe',
  GET_USER_RECIPES = 'get_user_recipes',
  GET_RECIPES = 'get_recipes',
  SEARCH_RECIPES = 'search_recipes';